---
version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2.arm64
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.2.arm64
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_LOG4J_LOGGERS: org.apache.zookeeper=WARN,org.apache.kafka=WARN,kafka=WARN,state.change.logger=WARN,kafka.controller=WARN
  orders-service:
    container_name: orders
    pull_policy: build
    build:
      context: services/orders
      dockerfile: ../../common/Dockerfile
    ports:
      - "8080:8080"
  catalogue-service:
    container_name: catalogue
    pull_policy: build
    build:
      context: services/catalogue
      dockerfile: ../../common/Dockerfile
    ports:
      - "8081:8080"
  email-service:
    container_name: email
    pull_policy: build
    build:
      context: services/email
      dockerfile: ../../common/Dockerfile
    ports:
      - "8082:8080"
  customers-service:
    container_name: customers
    pull_policy: build
    build:
      context: services/customers
      dockerfile: ../../common/Dockerfile